### ISSUE TITLE
Quiz portal: Finalize schema

### ISSUE THREAD

**Issue by SrivatsaRUpadhya** [incridea-23/incridea-server#21]
Make a quiz platform to conduct quizzes for first round of events

**Requirements**
**- Organizers**
[ ] Dashboard to create quiz
[ ] View submissions and results
[ ] Download results

**- Participants**
[ ] Answer quiz
[ ] View results

**Comment by AnirudhKaranth** [comment]
@swasthikshetty10  @SrivatsaRUpadhya 
#### Rough schema

![image](https://github.com/incridea-23/incridea-server/assets/97871145/52d224a1-2fba-455e-a9e8-5848cc96449e)

- question_type is enum [mcq, non_mcq]
- Results can be viewed through the Scores table

**Comment by SrivatsaRUpadhya** [comment]
Cool! 
But Could we have the options as string and the options are separated by commas. And we could have questions and quizzes as separate tables. Something like this: 
```
model Quiz {
    id              String           @id @default(cuid())
    name            String
    description     String?
    Questions       Question[]
    QuizSubmissions QuizSubmission[]
    //Add branch and other event details for which the quiz is conducted
}

model Question {
    id         String  @id @default(cuid())
    quizId     String
    Quiz       Quiz    @relation(fields: [quizId], references: [id], onDelete: Cascade)
    question   String
    options    String //Options separated by comma
    image      String?
    answer     Int     @default(-1) //Index of the correct answer (0-based)
    userChoice Int?    @default(-1) //Index of the user answer (0-based)
    userId     Int?
    User       User?   @relation(fields: [userId], references: [id], onDelete: SetNull)

    @@index([quizId])
    @@index([userId])
}

model QuizSubmission {
    id        String   @id @default(cuid())
    userId    Int
    User      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
    quizId    String
    Quiz      Quiz     @relation(fields: [quizId], references: [id], onDelete: Cascade)
    score     Int
    createdAt DateTime @default(now())

    @@index([userId])
    @@index([quizId])
}



```

**Comment by AnirudhKaranth** [comment]
Bro, what if we keep userchoice in seperate table like
Ex:  Userchoice {
          questionId string FK
          userChoice Int?    @default(-1) //Index of the user answer (0-based)
          userId     Int?
          User       User?
}
So that question details need not be repeated for each user.

**Comment by swasthikshetty10** [comment]
![image](https://github.com/incridea-23/incridea-server/assets/62538932/4c9fa665-a0fd-45e0-aa64-75dcb41b9e6b)

**Comment by 9964728107** [comment]
> ![image](https://private-user-images.githubusercontent.com/62538932/297139901-4c9fa665-a0fd-45e0-aa64-75dcb41b9e6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDcwODAsIm5iZiI6MTcwNTc0Njc4MCwicGF0aCI6Ii82MjUzODkzMi8yOTcxMzk5MDEtNGM5ZmE2NjUtYTBmZC00NWUwLWFhNjQtNzVkY2I0MWI5ZTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEwMzMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMWE1ZDU5YzBjZmNlMDI3YjlhYmUxYzhhNzJjMjI2NWFmNjM5MDA0ZjI4ZjVjZDY3ZDg4Y2ZlNmExOWMxYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9e2qsZwTUNsrzdy9DsZFMxAWJvuWlPOnPC_LROBqOV0)


//Schemas for Quizzing
enum QuestionType {
  MCQ
  FITB
}

model Quiz {
  id           String     @id @default(cuid())
  Round        Round      @relation(fields: [roundEventId, roundRoundNo], references: [eventId, roundNo])
  name         String
  description  String
  startTime    DateTime
  endTime      DateTime
  Question     Question[]
  roundEventId Int
  roundRoundNo Int

  @@index([roundEventId, roundRoundNo])
}

model Question {
  id             String       @id
  question       String
  image          String?
  points         Int @default(1)
  negativePoints Int @default(-1)
  type           QuestionType
  Quiz           Quiz         @relation(fields: [quizId], references: [id],onDelete: Cascade)
  quizId         String
  Options        Options[]
  FITBAns        FITBAns[]

  @@index([quizId])
}

model Options {
  id         String    @id @default(cuid())
  Question   Question  @relation(fields: [questionId], references: [id],onDelete: Cascade)
  questionId String
  value      String
  isAnswer   Boolean
  Answers    Answers[]

  @@index([questionId])
}

model Answers {
  Options  Options @relation(fields: [optionId], references: [id],onDelete: Cascade)
  optionId String  @id
  User     User    @relation(fields: [userId], references: [id],onDelete: Cascade)
  userId   Int

  @@index([optionId])
  @@index([userId])
}

model FITBAns {
  id         String   @id @default(cuid())
  value      String
  User       User     @relation(fields: [userId], references: [id],onDelete: Cascade)
  userId     Int
  Question   Question @relation(fields: [questionId], references: [id],onDelete: Cascade)
  questionId String

  @@index([userId])
  @@index([questionId])
}

check this vro...lemme know the things to correct...specially the RoundID as foreign key in Quiz model...

**Comment by satwikrprabhu** [comment]
the schema is ready already check the pr by Srivatsa
